databases:
  - name: budgetapp121
    databaseName: budgetapp121
    user: budgetapp121

services:
  - type: web
    name: Budget Monitor
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetapp121
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false