default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budgetapp

test:
  <<: *default
  database: Budgetapp_test

production:
  <<: *default
  database: Budgetapp_production
  username: Budgetapp
  password: <%= ENV["Budgetapp_DATABASE_PASSWORD"] %>
